{% set name = "cccc" %}
{% set version = "3.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: https://github.com/sarnold/cccc/archive/{{ version }}.tar.gz
  sha256: 2363948661a9ce6a8383f0f1f9e38548f9e19d31d7c31383e4a79925a868d14d

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

about:
  home: https://github.com/sarnold/cccc
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: C and C++ Code Counter (complexity and other metrics)

extra:
  recipe-maintainers:
    - sarnold
