@rem make_cccc_cli.bat
@rem This script runs at CCCC install time to generate a
@rem batch file for the command line interface which is 
@rem set up a sensible path for CCCC.
@rem Having the '>> %SCRIPT%' components hard after each
@rem line below is completed is ugly, but turns out to
@rem be necessary to avoid incorporation of trailing spaces
@rem into the various environment variables.
@echo off

set SCRIPT=cccc_cli.bat
echo @rem cccc_cli.bat> %SCRIPT%
echo @rem Script to start CCCC Command line environment>> %SCRIPT%
echo @rem This script is automatically generated by>> %SCRIPT%
echo @rem make_cccc_cli.bat when CCCC is installed.>> %SCRIPT%
echo @rem Users are welcome to edit it by hand after>> %SCRIPT%
echo @rem installation.>> %SCRIPT%
echo @echo off>> %SCRIPT%

echo rem Specify the location of the CCCC program files>> %SCRIPT%
echo set CCCCDIR=%1>> %SCRIPT%
echo rem Specify the user's initial working directory>> %SCRIPT%
echo set WORKDIR=%2>> %SCRIPT%

echo rem Set up a suitable path to enable the user to run>> %SCRIPT%
echo rem CCCC, the most common browsers, and basic tools>> %SCRIPT%
echo rem like notepad.exe.>> %SCRIPT%
echo set IEDIR="c:\Program Files\Internet Explorer">> %SCRIPT%
echo set MOZDIR="c:\Program Files\mozilla.org\Mozilla">> %SCRIPT%
echo set WINDIRS=%WINDIR%;%WINDIR%\command;%WINDIR%\system;%WINDIR%\system32>> %SCRIPT%
echo path %%CCCCDIR%%;%%IEDIR%%;%%MOZDIR%%;%%WINDIRS%%>> %SCRIPT%
echo type cccc_cli.msg >> %SCRIPT%
echo cd %%WORKDIR%%>> %SCRIPT%





