name: smoke

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add 64-bit mingw-w64 to the PATH
      run: |
        echo "c:/msys64/bin;c:/msys64/mingw64/bin" >> $GITHUB_PATH
        which gcc
      if: startsWith(matrix.os, 'win')

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Add requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Build and test
      run: |
        tox -e build

  windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Git describe
      id: ghd
      uses: proudust/gh-describe@v1

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: |
        .\build_msvc.bat --version ${{ steps.ghd.outputs.describe }}
        .\cccc.exe --version
